apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev
  namespace: flux-system
spec:
  interval: 1s
  path: ./   # points to this dev folder
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
