apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: akashns1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: nginx:1.20
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
 name: web-svc
 namespace: akashns1
spec:
  type: NodePort
  selector:
    app: web-app # POD lable
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31610
...        