apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-app
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/prod/UAT
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client 