apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-prod
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/nginx/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
